version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: recoagua_postgres
    environment:
      POSTGRES_USER: ${DB_USERNAME:-recoagua_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-recoagua_password}
      POSTGRES_DB: ${DB_DATABASE:-recoagua_db}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME:-recoagua_user} -d ${DB_DATABASE:-recoagua_db}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local